# This is a basic workflow to help you get started with Actions

name: Push detection to elastic

# # Controls when the workflow will run
#   - uses: actions/setup-python@v4
#         with:
#           python-version: '3.11.4'
on:
  push:
   branches:
     -main
   path: 
     '**.toml'
  workflow_dispatch:


jobs:
  elastic-detection-push:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Pushing to Elastic
        run: |
         python development/toml_to_json.py
      