# This is a basic workflow to help you get started with Actions

name: TOML Validation

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a multi-line script
        run: |
          python development/validation.py
          python development/mitre.py
