# This is a basic workflow to help you get started with Actions

name: TOML Validation

# # Controls when the workflow will run
#   - uses: actions/setup-python@v4
#         with:
#           python-version: '3.11.4'
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: python development/validation.py
        run: python development/mitre.py
