# This is a basic workflow to help you get started with Actions

name: Update detection to elastic

# # Controls when the workflow will run
#   - uses: actions/setup-python@v4
#         with:
#           python-version: '3.11.4'
on:
  push:
  workflow_dispatch:


jobs:
  elastic-detection-push:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
       - uses: actions/checkout@v4
         with:
          fetch-depth: 0

       - name: Get changed files
         id: changed-files
         uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0 # v46
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

       - name: List all changed files
         env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
         run: |
           for file in ${ALL_CHANGED_FILES}; do
             echo "$file was changed"
           done